/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiBrandRouteImport } from './routes/api/brand'
import { Route as ApiGenerationsRouteImport } from './routes/api/generations'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiPublishRouteImport } from './routes/api/publish'
import { Route as ApiSocialRouteImport } from './routes/api/social'
import { Route as LiveSlugRouteImport } from './routes/live.$slug'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAdsRouteImport } from './routes/studio/ads'
import { Route as StudioCalendarRouteImport } from './routes/studio/calendar'
import { Route as StudioInboxRouteImport } from './routes/studio/inbox'
import { Route as StudioOnboardingRouteImport } from './routes/studio/onboarding'
import { Route as StudioPostsRouteImport } from './routes/studio/posts'
import { Route as StudioPublishRouteImport } from './routes/studio/publish'
import { Route as StudioReelsRouteImport } from './routes/studio/reels'
import { Route as StudioShootRouteImport } from './routes/studio/shoot'
import { Route as StudioWebsiteRouteImport } from './routes/studio/website'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiGenerateAdRouteImport } from './routes/api/generate/ad'
import { Route as ApiGenerateCalendarRouteImport } from './routes/api/generate/calendar'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate/image'
import { Route as ApiGeneratePostRouteImport } from './routes/api/generate/post'
import { Route as ApiGenerateReelRouteImport } from './routes/api/generate/reel'
import { Route as ApiGenerateReplyRouteImport } from './routes/api/generate/reply'
import { Route as ApiGenerateWebsiteRouteImport } from './routes/api/generate/website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandRoute = ApiBrandRouteImport.update({
  id: '/api/brand',
  path: '/api/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerationsRoute = ApiGenerationsRouteImport.update({
  id: '/api/generations',
  path: '/api/generations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialRoute = ApiSocialRouteImport.update({
  id: '/api/social',
  path: '/api/social',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/live/$slug',
  path: '/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAdsRoute = StudioAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCalendarRoute = StudioCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInboxRoute = StudioInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOnboardingRoute = StudioOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPostsRoute = StudioPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPublishRoute = StudioPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReelsRoute = StudioReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => StudioRoute,
} as any)
const StudioShootRoute = StudioShootRouteImport.update({
  id: '/shoot',
  path: '/shoot',
  getParentRoute: () => StudioRoute,
} as any)
const StudioWebsiteRoute = StudioWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAdRoute = ApiGenerateAdRouteImport.update({
  id: '/api/generate/ad',
  path: '/api/generate/ad',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCalendarRoute = ApiGenerateCalendarRouteImport.update({
  id: '/api/generate/calendar',
  path: '/api/generate/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate/image',
  path: '/api/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePostRoute = ApiGeneratePostRouteImport.update({
  id: '/api/generate/post',
  path: '/api/generate/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReelRoute = ApiGenerateReelRouteImport.update({
  id: '/api/generate/reel',
  path: '/api/generate/reel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReplyRoute = ApiGenerateReplyRouteImport.update({
  id: '/api/generate/reply',
  path: '/api/generate/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateWebsiteRoute = ApiGenerateWebsiteRouteImport.update({
  id: '/api/generate/website',
  path: '/api/generate/website',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/brand': typeof ApiBrandRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/me': typeof ApiMeRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/social': typeof ApiSocialRoute
  '/live/$slug': typeof LiveSlugRoute
  '/p/$id': typeof PIdRoute
  '/studio/ads': typeof StudioAdsRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/inbox': typeof StudioInboxRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/posts': typeof StudioPostsRoute
  '/studio/publish': typeof StudioPublishRoute
  '/studio/reels': typeof StudioReelsRoute
  '/studio/shoot': typeof StudioShootRoute
  '/studio/website': typeof StudioWebsiteRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/generate/ad': typeof ApiGenerateAdRoute
  '/api/generate/calendar': typeof ApiGenerateCalendarRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/post': typeof ApiGeneratePostRoute
  '/api/generate/reel': typeof ApiGenerateReelRoute
  '/api/generate/reply': typeof ApiGenerateReplyRoute
  '/api/generate/website': typeof ApiGenerateWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/api/brand': typeof ApiBrandRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/me': typeof ApiMeRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/social': typeof ApiSocialRoute
  '/live/$slug': typeof LiveSlugRoute
  '/p/$id': typeof PIdRoute
  '/studio/ads': typeof StudioAdsRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/inbox': typeof StudioInboxRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/posts': typeof StudioPostsRoute
  '/studio/publish': typeof StudioPublishRoute
  '/studio/reels': typeof StudioReelsRoute
  '/studio/shoot': typeof StudioShootRoute
  '/studio/website': typeof StudioWebsiteRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/generate/ad': typeof ApiGenerateAdRoute
  '/api/generate/calendar': typeof ApiGenerateCalendarRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/post': typeof ApiGeneratePostRoute
  '/api/generate/reel': typeof ApiGenerateReelRoute
  '/api/generate/reply': typeof ApiGenerateReplyRoute
  '/api/generate/website': typeof ApiGenerateWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/brand': typeof ApiBrandRoute
  '/api/generations': typeof ApiGenerationsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/me': typeof ApiMeRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/publish': typeof ApiPublishRoute
  '/api/social': typeof ApiSocialRoute
  '/live/$slug': typeof LiveSlugRoute
  '/p/$id': typeof PIdRoute
  '/studio/ads': typeof StudioAdsRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/inbox': typeof StudioInboxRoute
  '/studio/onboarding': typeof StudioOnboardingRoute
  '/studio/posts': typeof StudioPostsRoute
  '/studio/publish': typeof StudioPublishRoute
  '/studio/reels': typeof StudioReelsRoute
  '/studio/shoot': typeof StudioShootRoute
  '/studio/website': typeof StudioWebsiteRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/generate/ad': typeof ApiGenerateAdRoute
  '/api/generate/calendar': typeof ApiGenerateCalendarRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/generate/post': typeof ApiGeneratePostRoute
  '/api/generate/reel': typeof ApiGenerateReelRoute
  '/api/generate/reply': typeof ApiGenerateReplyRoute
  '/api/generate/website': typeof ApiGenerateWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/examples'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/studio'
    | '/api/brand'
    | '/api/generations'
    | '/api/live'
    | '/api/me'
    | '/api/messages'
    | '/api/plan'
    | '/api/publish'
    | '/api/social'
    | '/live/$slug'
    | '/p/$id'
    | '/studio/ads'
    | '/studio/calendar'
    | '/studio/inbox'
    | '/studio/onboarding'
    | '/studio/posts'
    | '/studio/publish'
    | '/studio/reels'
    | '/studio/shoot'
    | '/studio/website'
    | '/studio/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/generate/ad'
    | '/api/generate/calendar'
    | '/api/generate/image'
    | '/api/generate/post'
    | '/api/generate/reel'
    | '/api/generate/reply'
    | '/api/generate/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/examples'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/api/brand'
    | '/api/generations'
    | '/api/live'
    | '/api/me'
    | '/api/messages'
    | '/api/plan'
    | '/api/publish'
    | '/api/social'
    | '/live/$slug'
    | '/p/$id'
    | '/studio/ads'
    | '/studio/calendar'
    | '/studio/inbox'
    | '/studio/onboarding'
    | '/studio/posts'
    | '/studio/publish'
    | '/studio/reels'
    | '/studio/shoot'
    | '/studio/website'
    | '/studio'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/generate/ad'
    | '/api/generate/calendar'
    | '/api/generate/image'
    | '/api/generate/post'
    | '/api/generate/reel'
    | '/api/generate/reply'
    | '/api/generate/website'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/examples'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/studio'
    | '/api/brand'
    | '/api/generations'
    | '/api/live'
    | '/api/me'
    | '/api/messages'
    | '/api/plan'
    | '/api/publish'
    | '/api/social'
    | '/live/$slug'
    | '/p/$id'
    | '/studio/ads'
    | '/studio/calendar'
    | '/studio/inbox'
    | '/studio/onboarding'
    | '/studio/posts'
    | '/studio/publish'
    | '/studio/reels'
    | '/studio/shoot'
    | '/studio/website'
    | '/studio/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/generate/ad'
    | '/api/generate/calendar'
    | '/api/generate/image'
    | '/api/generate/post'
    | '/api/generate/reel'
    | '/api/generate/reply'
    | '/api/generate/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExamplesRoute: typeof ExamplesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiBrandRoute: typeof ApiBrandRoute
  ApiGenerationsRoute: typeof ApiGenerationsRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiPublishRoute: typeof ApiPublishRoute
  ApiSocialRoute: typeof ApiSocialRoute
  LiveSlugRoute: typeof LiveSlugRoute
  PIdRoute: typeof PIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiGenerateAdRoute: typeof ApiGenerateAdRoute
  ApiGenerateCalendarRoute: typeof ApiGenerateCalendarRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGeneratePostRoute: typeof ApiGeneratePostRoute
  ApiGenerateReelRoute: typeof ApiGenerateReelRoute
  ApiGenerateReplyRoute: typeof ApiGenerateReplyRoute
  ApiGenerateWebsiteRoute: typeof ApiGenerateWebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand': {
      id: '/api/brand'
      path: '/api/brand'
      fullPath: '/api/brand'
      preLoaderRoute: typeof ApiBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generations': {
      id: '/api/generations'
      path: '/api/generations'
      fullPath: '/api/generations'
      preLoaderRoute: typeof ApiGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social': {
      id: '/api/social'
      path: '/api/social'
      fullPath: '/api/social'
      preLoaderRoute: typeof ApiSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/live/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/ads': {
      id: '/studio/ads'
      path: '/ads'
      fullPath: '/studio/ads'
      preLoaderRoute: typeof StudioAdsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/calendar': {
      id: '/studio/calendar'
      path: '/calendar'
      fullPath: '/studio/calendar'
      preLoaderRoute: typeof StudioCalendarRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/inbox': {
      id: '/studio/inbox'
      path: '/inbox'
      fullPath: '/studio/inbox'
      preLoaderRoute: typeof StudioInboxRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/onboarding': {
      id: '/studio/onboarding'
      path: '/onboarding'
      fullPath: '/studio/onboarding'
      preLoaderRoute: typeof StudioOnboardingRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/posts': {
      id: '/studio/posts'
      path: '/posts'
      fullPath: '/studio/posts'
      preLoaderRoute: typeof StudioPostsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/publish': {
      id: '/studio/publish'
      path: '/publish'
      fullPath: '/studio/publish'
      preLoaderRoute: typeof StudioPublishRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/reels': {
      id: '/studio/reels'
      path: '/reels'
      fullPath: '/studio/reels'
      preLoaderRoute: typeof StudioReelsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/shoot': {
      id: '/studio/shoot'
      path: '/shoot'
      fullPath: '/studio/shoot'
      preLoaderRoute: typeof StudioShootRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/website': {
      id: '/studio/website'
      path: '/website'
      fullPath: '/studio/website'
      preLoaderRoute: typeof StudioWebsiteRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/ad': {
      id: '/api/generate/ad'
      path: '/api/generate/ad'
      fullPath: '/api/generate/ad'
      preLoaderRoute: typeof ApiGenerateAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/calendar': {
      id: '/api/generate/calendar'
      path: '/api/generate/calendar'
      fullPath: '/api/generate/calendar'
      preLoaderRoute: typeof ApiGenerateCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/image': {
      id: '/api/generate/image'
      path: '/api/generate/image'
      fullPath: '/api/generate/image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/post': {
      id: '/api/generate/post'
      path: '/api/generate/post'
      fullPath: '/api/generate/post'
      preLoaderRoute: typeof ApiGeneratePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/reel': {
      id: '/api/generate/reel'
      path: '/api/generate/reel'
      fullPath: '/api/generate/reel'
      preLoaderRoute: typeof ApiGenerateReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/reply': {
      id: '/api/generate/reply'
      path: '/api/generate/reply'
      fullPath: '/api/generate/reply'
      preLoaderRoute: typeof ApiGenerateReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/website': {
      id: '/api/generate/website'
      path: '/api/generate/website'
      fullPath: '/api/generate/website'
      preLoaderRoute: typeof ApiGenerateWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioAdsRoute: typeof StudioAdsRoute
  StudioCalendarRoute: typeof StudioCalendarRoute
  StudioInboxRoute: typeof StudioInboxRoute
  StudioOnboardingRoute: typeof StudioOnboardingRoute
  StudioPostsRoute: typeof StudioPostsRoute
  StudioPublishRoute: typeof StudioPublishRoute
  StudioReelsRoute: typeof StudioReelsRoute
  StudioShootRoute: typeof StudioShootRoute
  StudioWebsiteRoute: typeof StudioWebsiteRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAdsRoute: StudioAdsRoute,
  StudioCalendarRoute: StudioCalendarRoute,
  StudioInboxRoute: StudioInboxRoute,
  StudioOnboardingRoute: StudioOnboardingRoute,
  StudioPostsRoute: StudioPostsRoute,
  StudioPublishRoute: StudioPublishRoute,
  StudioReelsRoute: StudioReelsRoute,
  StudioShootRoute: StudioShootRoute,
  StudioWebsiteRoute: StudioWebsiteRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExamplesRoute: ExamplesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiBrandRoute: ApiBrandRoute,
  ApiGenerationsRoute: ApiGenerationsRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiMeRoute: ApiMeRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiPublishRoute: ApiPublishRoute,
  ApiSocialRoute: ApiSocialRoute,
  LiveSlugRoute: LiveSlugRoute,
  PIdRoute: PIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiGenerateAdRoute: ApiGenerateAdRoute,
  ApiGenerateCalendarRoute: ApiGenerateCalendarRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGeneratePostRoute: ApiGeneratePostRoute,
  ApiGenerateReelRoute: ApiGenerateReelRoute,
  ApiGenerateReplyRoute: ApiGenerateReplyRoute,
  ApiGenerateWebsiteRoute: ApiGenerateWebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
